// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tapajmlapibpfopbqkgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcGFqbWxhcGlicGZvcGJxa2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjU3NzMsImV4cCI6MjA1OTgwMTc3M30.LTrChfgnUncLApffGLLAY8dYDnMeyw_M61AYvDSbsKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);